# wrangler.toml

name                   = "sink"
main                   = "dist/_worker.js"          # votre Worker Nitro généré
compatibility_date     = "2025-05-08"
compatibility_flags    = ["nodejs_compat"]
keep_vars              = true
upload_source_maps     = true
pages_build_output_dir = "dist/public"              # dossier Pages pour vos assets statiques

[assets]
binding   = "ASSETS"
directory = "dist/public"

[ai]
binding = "AI"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "sink"

[[kv_namespaces]]
binding = "KV"
id      = "ef93d42dc4b34969bab404d2e80f8dd3"
