name               = "sink"
compatibility_date = "2025-05-08"

[build]
  command   = "npm install && npm run build"
  directory = "dist/public"     # vos assets Nuxt
  functions = "dist/_worker.js" # le Worker Nitro généré

[functions]
  # Active la compatibilité Node.js pour les modules "node:buffer", etc.
  compatibility_date  = "2025-05-08"
  compatibility_flags = ["nodejs_compat"]
