name                = "sink"
compatibility_date  = "2025-05-08"
compatibility_flags = ["nodejs_compat"]

# Build configuration for Cloudflare Pages + Functions
[build]
  command   = "npm install && npm run build"
  # dossier statique généré par Nuxt
  directory = "dist/public"
  # chemin vers le Worker généré par Nitro
  functions = "dist/_worker.js"
